### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by snicoll** [merapar/spring-boot-starter-graphql#11]
Following a request to add this starter to the 3rd party community list https://github.com/spring-projects/spring-boot/pull/8026, could you please consider renaming this project to `graphql-spring-boot-starter`? 

Also, `graphql-core` is quite unusual for the name of the starter (I am guessing that artifact is the starter right?).

More info in [our documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming)

**Comment by janfockaert** [comment]
Thanks for the feedback, we'll pick this up in next release.

Good point about the directory structure with `graphql-core`. We'll change this into `starter` and `sample` so it's more clearer. Or do you think `spring-boot-starter` and `spring-boot-sample` are more appropriate?

**Comment by snicoll** [comment]
If you name it `spring-boot-starter` we will end up in the same situation wouldn't it? (Much worse actually). The name of the directory usually is the same name as the `artifactid` and that documentation I referenced mentions that we prefer to use the spring-boot prefix for official artifacts. 

I'd use the same name as my suggestion for the project. Or you could rename the project to something else or not rename it.  But I'd aim for consistency regardless.

**Comment by janfockaert** [comment]
Sorry for the confusion, the new project name will be `graphql-spring-boot-starter` like your proposal. I meant the directory naming inside the project as `starter` and `sample` instead now `graphql-core` and `graphql-sample`.

**Comment by snicoll** [comment]
If you're asking for my opinion, starter isn't a great name for an artifactid. Usually there is some sort of qualifier. "starter.jar" is a bit weird isn't it? `graphql-spring-boot-starter` is what I would do. You could rename the project to `graphql-spring-boot` or something.

**Comment by snicoll** [comment]
@janfockaert it's been several months now. Changing the name of the github project and the build config should take you a few minutes. Is there anything that's preventing that change?

**Comment by aidanvanlatestein** [comment]
Apologies we missed this one will pick this up asap.

**Comment by janfockaert** [comment]
Sorry for the delay @snicoll, can you check the project again, we renamed all dependencies.

**Comment by snicoll** [comment]
Thanks
