### ISSUE TITLE
Provide instructions to run the project

### ISSUE THREAD

**Issue by rmzoni** [merapar/spring-boot-starter-graphql#17]
Hi,

I´m trying to run the project using spring boot by running the jar direct.

I´m compiling the project with mvn clean install and the build happen fine.

When I´m trying to run java -jar spring-boot-starter-graphql-sample-1.0.2-alpha.jar and I´m getting this error:

**_java -jar spring-boot-starter-graphql-sample-1.0.2-alpha.jar
No major manifest attribute on spring-boot-starter-graphql-sample-1.0.2-alpha.jar_**

What I´m getting wrong?

**Comment by janfockaert** [comment]
Thanks for trying the sample project. We forgot to add "spring-boot-maven-plugin" to the maven build step. Will correct this, so an executable jar will be generated.

**Comment by rmzoni** [comment]
Thanks :). Trying again soon!!!!!
