### ISSUE TITLE
ThreadLocals and executors

### ISSUE THREAD

**Issue by martin-g** [merapar/spring-boot-starter-graphql#18]
Hi,

I'm experimenting with GraphQL and while migrating my REST (based on Spring MVC) app I faced an issue with Spring Security.
In my REST app I am able to use `SecurityContextHolder.getContext().getAuthentication().getPrincipal()` to get a reference to the currently logged in user.
But in GraphQL it seems the DataFetchers are executed in custom threads and this information is not available.
I guess the proper way would be to put such kind of information to the DataFetchingEnvironment that is passed to the DataFetchers. How? 
Or is there a better approach ?

Thank you for this library!

**Comment by martin-g** [comment]
I see that https://github.com/merapar/spring-boot-starter-graphql/blob/master/graphql-core/src/main/java/com/merapar/graphql/executor/GraphQlExecutorImpl.java is conditional, i.e. I can provide my own impl.
It would be nice if https://github.com/merapar/spring-boot-starter-graphql/blob/master/graphql-core/src/main/java/com/merapar/graphql/executor/GraphQlExecutorImpl.java#L52 is `protected` and the return type is just `ExecutionStrategy`.
This way I'd be able to use `SimpleExecutionStrategy` and execute the processing in the same thread. I'm not sure whether this will lead to any other problems though!

**Comment by janfockaert** [comment]
Thanks for the feedback!

For solving this you can have two approaches:
- The simple execution strategy, like you proposed. Committed changes so you can override this.
- Override the `beforeExecuteRequest` method to place custom authentication details in context object. Added this to the sample [CustomGraphQlExecutorImpl.java](https://github.com/merapar/spring-boot-starter-graphql/blob/master/graphql-sample/src/main/java/com/merapar/graphql/sample/CustomGraphQlExecutorImpl.java)

GraphQL itself promotes the second approach using the context object for passing authorisation details: http://graphql.org/learn/authorization/

**Comment by martin-g** [comment]
Thank you!
I'll test it soon and let you know if I find more ideas for improvement!
