### ISSUE TITLE
Issue with Filtering for String -> wrong type

### ISSUE THREAD

**Issue by MartinX3** [merapar/spring-boot-starter-graphql#27]
```
curl --request POST \
 --url http://localhost:8080/v1/graphql \
 --header 'content-type: application/json' \
 --data '{"query":"query {categories(filter: { name: \"Dried\" }) {id name}}","variables":"{}"}';
```
returns

`{"errors":[{"validationErrorType":"WrongType","locations":[{"line":1,"column":19}],"errorType":"ValidationError","message":"Validation error of type WrongType: argument value ObjectValue{objectFields=[ObjectField{name='name', value=StringValue{value='Dried'}}]} has wrong type"}],"data":null}`

The code for the filtering is
```
        filterCategoryInputType = GraphQLInputObjectType.newInputObject().name("filterCategoryInput")
                .field(GraphQLInputObjectField.newInputObjectField().name("id").type(Scalars.GraphQLLong).build())
                .field(GraphQLInputObjectField.newInputObjectField().name("name").type(Scalars.GraphQLString).build())
                .build();
```

and

```
        categoriesField = GraphQLFieldDefinition.newFieldDefinition()
                .name("categories").description("Provide an overview of all categories")
                .type(new GraphQLList(categoryType))
                .argument(GraphQLArgument.newArgument().name(GraphQlFieldsHelper.FILTER).type(filterCategoryInputType).build())
                .dataFetcher(environment -> categoryDataFetcher.getCategorysByFilter(GraphQlFieldsHelper.getFilterMap(environment)))
                .build();
```

It doesn't go into the method "getCategorysByFilter", when i filter for the name.
Only, if I filter for the ID.

**Comment by martin-g** [comment]
This question is for https://github.com/graphql-java/graphql-java since it is not Spring-Boot specific.

**Comment by MartinX3** [comment]
Thank you very much for your fast response.

I don't know why, but after I recompiled two times this problem disappeared and now it uses the filter method.
Very weird.
