### ISSUE TITLE
\ or new line character not allowed in curl statement

### ISSUE THREAD

**Issue by MartinX3** [merapar/spring-boot-starter-graphql#28]
The Character '\' for new line is not allowed in the curl statement, if it is put inside the json.

curl --request POST   --url http://localhost:8080/v1/graphql \    **_<- Allowed._**
    --header 'content-type: application/json' \    **_<- Allowed._**
    --data '{"query":"query {categories(filter: { name: \"Dried\" })  \    **_<- This one is not allowed._**
        {id name}}","variables":"{}"}';

Edit: I thought, that a new Line isn't a Problem in a JSON.

Edit0:
Same with an invisible new line character.

`{"timestamp":1503920520738,"status":400,"error":"Bad Request","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"JSON parse error: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value; nested exception is com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value\n at [Source: java.io.PushbackInputStream@1b1e7e6; line: 1, column: 29]","path":"/v1/graphql"}`

**Comment by janfockaert** [comment]
The JSON is incorrect encoded, can you try with the application [GraphiQl](https://github.com/skevy/graphiql-app) and try to execute the query.

**Comment by MartinX3** [comment]
Thank you for your fast replay! :)

I wrote
`{categories(filter: { name: "Dried" }) \
{id name}}`
and there it worked.

if I write \n, I get a error message not similar to the one in intelliJ.

**Comment by martin-g** [comment]
I don't understand why this issue is logged here.
To me it looks like bad usage of `curl` - `\` should not be used inside the single quoted string.
But even if I am wrong and this curl command is correct then this is a problem in graphql-java where the query parsing happens.
This project is about providing Spring goodies to graphql-java.

**Comment by MartinX3** [comment]
Thank you for your help and sorry, that I'd stole your time.
I will ask the graphql-developers. :)

Because the \ is allowed in JSON and GraphiQl has no problems with it. :)

**Comment by janfockaert** [comment]
ok, no problem
